Extended to set custom Server ID
robinmanuelthiel/speedtest pull request #16
Opened 2024-03-05 12:49 UTC by madnuttah

Script and yaml files edited, I hope it's fine.

2024-03-05 12:50 UTC, madnuttah commented
The concerns regarding the `wait` command could be circumvented by (mis)using a healthcheck-script like I did [here](https://github.com/madnuttah/unbound-docker-stats/blob/main/README.md#instructions)

2024-03-05 13:01 UTC, madnuttah commented
My apologies, apparently this is new to me.

2024-05-30 07:56 UTC, bazzani commented
Hi @robinmanuelthiel and @madnuttah 

I have been looking at this repo too and I want to introduce a similar change to supply a hostname (with `-o` argument) to the `speedtest` command optionally, and I plan to open a PR soon from my fork.

---

Concerning this PR, I tested your changes locally @madnuttah and I observed a problem where the docker container fails if I do not specify the server ID.  I think it would be good to make this ability to add a server ID optional, and if it is missing the the regular `speedtest` CLI command should be invoked without the `-s` argument.

Container logs:

```
Running a Speed Test...
2024-05-30T07:41:46.102927881Z Thu May 30 07:41:46 2024
2024-05-30T07:41:46.107768923Z speedtest: Missing argument for option: -s
2024-05-30T07:41:46.149092423Z Unable to retrieve JSON results from speedtest
2024-05-30T07:41:46.149114881Z Running next test in 1800s...
2024-05-30T07:41:46.149116256Z 
```

---

p.s. the similar change I made can be found at
- https://github.com/bazzani/speedtest/commit/2033353a1b671a3be0b7de876376f49c2cbe9568

2024-06-01 10:59 UTC, robinmanuelthiel commented
Yeah, if we introduce Server ID and URL, I would like to see them as _optional_ parameters as well. This implementation here requires them.

2024-06-01 11:02 UTC, robinmanuelthiel requested changes
Thank you very much for this change! I would like to see the server ID as an _optional_ parameter, though. Can you make it optional yourself, or do you want help with that?

2024-06-01 11:02 UTC, robinmanuelthiel commented on speedtest.sh
> +#!/bin/bash
Any reason why you changed from shell to bash?

2024-06-01 11:02 UTC, robinmanuelthiel commented on speedtest.sh
> +        echo "Saving values to database..."
Pls remove added sapces here

2024-06-01 11:02 UTC, robinmanuelthiel commented on speedtest.sh
> +            --data-binary "ping,host=$HOSTNAME value=$PING $DATE"
Pls remove added sapces here

2024-06-09 11:21 UTC, robinmanuelthiel commented
> Hi @robinmanuelthiel and @madnuttah
> 
> I have been looking at this repo too and I want to introduce a similar change to supply a hostname (with `-o` argument) to the `speedtest` command optionally, and I plan to open a PR soon from my fork.
> 
> Concerning this PR, I tested your changes locally @madnuttah and I observed a problem where the docker container fails if I do not specify the server ID. I think it would be good to make this ability to add a server ID optional, and if it is missing the the regular `speedtest` CLI command should be invoked without the `-s` argument.
> 
> Container logs:
> 
> ```
> Running a Speed Test...
> 2024-05-30T07:41:46.102927881Z Thu May 30 07:41:46 2024
> 2024-05-30T07:41:46.107768923Z speedtest: Missing argument for option: -s
> 2024-05-30T07:41:46.149114881Z Running next test in 1800s...
> 2024-05-30T07:41:46.149116256Z 
> ```
> 
> p.s. the similar change I made can be found at
> 
> * [bazzani@2033353](https://github.com/bazzani/speedtest/commit/2033353a1b671a3be0b7de876376f49c2cbe9568)

This looks promising. Can you create a PR from your repo back into this one?

2024-06-09 12:55 UTC, bazzani commented
> > p.s. the similar change I made can be found at
> > 
> > * [bazzani@2033353](https://github.com/bazzani/speedtest/commit/2033353a1b671a3be0b7de876376f49c2cbe9568)
> 
> This looks promising. Can you create a PR from your repo back into this one?

Hi @robinmanuelthiel, may I ask you to please clarify that you are referring to my suggested change?
- https://github.com/bazzani/speedtest/commit/2033353a1b671a3be0b7de876376f49c2cbe9568

If so, I can work on this, and also add support for the `-s` flag at the same time
**although providing them must be mutually exclusive or _this causes an error_ when running the speedtest cli with both `-o` and `-s` provided** 👇 

- ```sh
  speedtest --accept-license --accept-gdpr -f json -s 28910 -o lg-tok.fdcservers.net
  [2024-06-09 21:50:15.193] [error] Only one server selection can be specified
  ```

2024-06-09 13:07 UTC, robinmanuelthiel commented
Yes, exactly. To me it's important, that I also works without specifying any server name or IP.

2024-06-09 13:13 UTC, bazzani commented
> Yes, exactly. To me it's important, that I also works without specifying any server name or IP.

100%, I will open the PR soon enough, after giving it a thorough test locally.

2024-06-09 16:13 UTC, madnuttah commented
Hey there and sorry for my late reply. I must confess this was quite rushed. It was working so I submitted the PR without any further tests, as I wrote it did what I wanted. I'm sorry if it didn't meet the quality you've expected. As I'm doing much better again, I'm getting a take on this again.

2024-06-09 16:16 UTC, robinmanuelthiel commented
@bazzani Not sure, if I like the build part in the Docker Compose file, as I wanted to give an example, how to use the container easily in Docker Compose file. Building it yourself, would make it harder. But we could maybe add another examle file for self-building or just use both, `image` and `build` https://docs.docker.com/compose/compose-file/build/#using-build-and-image

2024-06-09 19:12 UTC, robinmanuelthiel commented
> Hey there and sorry for my late reply. I must confess this was quite rushed. It was working so I submitted the PR without any further tests, as I wrote it did what I wanted. I'm sorry if it didn't meet the quality you've expected. As I'm doing much better again, I'm getting a take on this again.

Hey no worries - thanks for the contribution. We are working on this together! 💪

2024-06-10 03:34 UTC, bazzani commented
> @bazzani Not sure, if I like the build part in the Docker Compose file, as I wanted to give an example, how to use the container easily in Docker Compose file. Building it yourself, would make it harder. But we could maybe add another examle file for self-building or just use both, `image` and `build` https://docs.docker.com/compose/compose-file/build/#using-build-and-image

I see what you mean @robinmanuelthiel, thanks for the input and helping me consider the other optionsyou proposed.
I think I was perhaps a tad too deep in the developer mindset, and not enough in a consumer (_of the service_) mindset.

I will review that link you sent and play about a bit with the image and build approach.

2024-06-10 03:37 UTC, bazzani commented
> Hey there and sorry for my late reply. I must confess this was quite rushed. It was working so I submitted the PR without any further tests, as I wrote it did what I wanted. I'm sorry if it didn't meet the quality you've expected. As I'm doing much better again, I'm getting a take on this again.

Thank you for the PR @madnuttah, I do appreciate your changes as it helped me to understand the project more, and made me more curious as to how we can extend it by working together. **OSS is the best**!

2024-06-10 15:56 UTC, madnuttah commented on README.md
> +| `TESTSERVER_ID`      | `61186`              | ServerID, you get this by inspecting your ISP entry [Ookla Speedtest Website](speedtest.net)                  |
Before I start, some questions. Do you prefer having a generic string here or do you have a completely different approach in mind? I just picked one. I guess describing better how to get a ServerID is also necessary here.

2024-06-10 16:00 UTC, madnuttah commented on speedtest.sh
> +        echo "Saving values to database..."
Will do

2024-06-10 16:00 UTC, madnuttah commented on speedtest.sh
> +            --data-binary "ping,host=$HOSTNAME value=$PING $DATE"
Also here

2024-06-12 18:38 UTC, madnuttah commented
@bazzani it seems like you invested way more time into this and the script looks better already than what I have here right now. I'll close this, also because of a lack of time. Sorry, I shouldn't have done this that time.

2024-06-12 18:38 UTC, closed without merging

2024-06-13 09:30 UTC, robinmanuelthiel commented
> Sorry, I shouldn't have done this that time.

I disagree! Your effort kicked it all off. Can't wait to see this feature here soon. Thanks for your work @madnuttah! Keep it coming. (both feedback, issues and code contributions)

2024-06-16 11:59 UTC, robinmanuelthiel commented
@bazzani, are you still planning to create a PR for the Server ID?

2024-06-16 13:19 UTC, bazzani commented
> @bazzani, are you still planning to create a PR for the Server ID?

Hi @robinmanuelthiel i am indeed. I started working on it last week and got stuck on a few shell scripting logic challenges (due to the two mutually exclusive optional flags). I then got sick on Friday so I have not had a chance to complete it yet.

I will look at it tomorrow and get something in a PR for your review.

2024-06-17 05:19 UTC, bazzani commented
FYI @robinmanuelthiel @madnuttah #19